config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :usuarios
  root 'home#index'
  get 'fundos', to: 'fundos#index'
  get 'fundos/:ticker', to: 'fundos#recupera'
  get 'integra/:ticker', to: 'fundos#integra'
  post 'fundos/popula', to: 'fundos#popula'
  resources :dados_fundos
  get 'noticias/fii/:id', to: "noticias#fii"
  get 'noticias/fii/', to: "noticias#fii"

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'sessions#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/dados_fundo.rb
class DadosFundo < ApplicationRecord
	require_relative 'arquivo'

	def self.pegarLinksDoXml(cnpj)
		url = 'https://fnet.bmfbovespa.com.br/fnet/publico/pesquisarGerenciadorDocumentosCVM?paginaCertificados=false&tipoFundo=1&administrador=&cnpjFundo='.concat(cnpj,'&idCategoriaDocumento=14&idTipoDocumento=41&idEspecieDocumento=0&situacao=&cnpj=&dataReferencia=&dataInicial=&dataFinal=&idModalidade=&palavraChave=')
		arquivo = Arquivo.new(url)
		arquivo.abrirArquivo
		arquivo.aplicarNokogiriSite
		documento = arquivo.getDocumento
		links = documento.css('a[title="Download do Documento"]').map { |link| link['href'] }
		if links.length < 1
			return 'Fundo não foi achado'
		elsif documento
			return links
		else
			return documento.getErroTraduzido || documento.getErro
		end
	end

	def self.gerarDocumentoDadoFundo(caminhoArquivo)
		url = 'https://fnet.bmfbovespa.com.br/fnet/publico/'.concat(caminhoArquivo)
		arquivo = Arquivo.new(url)
		arquivo.abrirArquivo
		arquivo.aplicarNokogiriXML
		documento = arquivo.getDocumento
		return documento
	end

	def self.gerarItemDadoFundo(documento)
		if documento
			item = {}
			item['codigoAtivo'] = documento.at_css('CodNegociacaoCota').content
			item['rendimento'] = documento.at_css('ValorProventoCota').content
			item['diaPagamento'] = documento.at_css('DataPagamento').content
			item['dataBase'] = documento.at_css('DataBase').content
			item['cnpj'] = documento.at_css('CNPJFundo').content
			return item
		else
			return documento.getErroTraduzido || documento.getErro
		end
	end

	def self.gerarDadosFundo(cnpj)
		linksComRendimento = pegarLinksDoXml(cnpj)
		dadosFundo = []
		if linksComRendimento.is_a?(Array)
			linksComRendimento.first(10).each do |caminhoArquivo|
				dadosFundo.push(gerarItemDadoFundo(gerarDocumentoDadoFundo(caminhoArquivo)))
			end
		else
			puts linksComRendimento
		end
		return dadosFundo
	end

	def self.salvarDados(listaResultados)
		if (listaResultados.kind_of?(Array))
			listaResultados.each do |item|
				dataBase = item['dataBase']
				codigoAtivo = item['codigoAtivo']
				acao = DadosFundo.where(:codigoAtivo => codigoAtivo, :dataBase => dataBase).first_or_create do |fundo|
					fundo.rendimento = item['rendimento']
					fundo.diaPagamento = item['diaPagamento']
					fundo.cnpj = item['cnpj']
				end
			end
			return true
		else
			return false
		end
  end

 def self.pega_rendimentos(cnpj)
   rendimentos = DadosFundo.where(['cnpj = :c', { c: cnpj }])

   rendimentos unless rendimentos.nil?

   lista_rendimentos = DadosFundo.gerarDadosFundo(cnpj)
   DadosFundo.salvarDados(lista_rendimentos)

   rendimentos = DadosFundo.where(['cnpj = :c', { c: cnpj }])
   rendimentos
 end

end

app/controllers/dados_fundos_controller.rb
class DadosFundosController < ApplicationController
	before_action :set_dados_fundo, only: [:show, :edit, :update, :destroy]

	# GET /dados_fundos
	# GET /dados_fundos.json
	def pegarCnpjEChamarScrap
		if(params.has_key?(:cnpj))
			cnpj = params[:cnpj]
			puts "O CNPJ É: " + cnpj
			if (cnpj != "")
				listaFundos = DadosFundo.gerarDadosFundo(cnpj)
				DadosFundo.salvarDados(listaFundos)
				return listaFundos
			else
				return "Erro: Nenhum código foi informado"
			end
		else
			return "Erro: Informe o código do ativo pelo parâmetro 'codigo'"
		end
	end

	def index
		@dados_fundos = DadosFundo.all
		@ngiri = pegarCnpjEChamarScrap
	end
	
	# GET /dados_fundos/1
	# GET /dados_fundos/1.json
	def show
	end

	# GET /dados_fundos/new
	def new
		@dados_fundo = DadosFundo.new
	end

	# GET /dados_fundos/1/edit
	def edit
	end

	# POST /dados_fundos
	# POST /dados_fundos.json
	def create
		@dados_fundo = DadosFundo.new(dados_fundo_params)

		respond_to do |format|
			if @dados_fundo.save
				format.html { redirect_to @dados_fundo, notice: 'Dados fundo was successfully created.' }
				format.json { render :show, status: :created, location: @dados_fundo }
			else
				format.html { render :new }
				format.json { render json: @dados_fundo.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /dados_fundos/1
	# PATCH/PUT /dados_fundos/1.json
	def update
		respond_to do |format|
			if @dados_fundo.update(dados_fundo_params)
				format.html { redirect_to @dados_fundo, notice: 'Dados fundo was successfully updated.' }
				format.json { render :show, status: :ok, location: @dados_fundo }
			else
				format.html { render :edit }
				format.json { render json: @dados_fundo.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /dados_fundos/1
	# DELETE /dados_fundos/1.json
	def destroy
		@dados_fundo.destroy
		respond_to do |format|
			format.html { redirect_to dados_fundos_url, notice: 'Dados fundo was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_dados_fundo
		@dados_fundo = DadosFundo.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def dados_fundo_params
		params.require(:dados_fundo).permit(:codigoAtivo, :rendimento, :dataBase, :diaPagamento, :cnpj)
	end
end

app/helpers/dados_fundos_helper.rb
module DadosFundosHelper
end

app/views/dados_fundos/_form.html.erb
<%= form_with(model: dados_fundo, local: true) do |form| %>
  <% if dados_fundo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dados_fundo.errors.count, "error") %> prohibited this dados_fundo from being saved:</h2>

      <ul>
      <% dados_fundo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigoAtivo %>
    <%= form.text_field :codigoAtivo %>
  </div>

  <div class="field">
    <%= form.label :rendimento %>
    <%= form.text_field :rendimento %>
  </div>

  <div class="field">
    <%= form.label :dataBase %>
    <%= form.text_field :dataBase %>
  </div>

  <div class="field">
    <%= form.label :diaPagamento %>
    <%= form.text_field :diaPagamento %>
  </div>

  <div class="field">
    <%= form.label :cnpj %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dados_fundos/edit.html.erb
<h1>Editing Dados Fundo</h1>

<%= render 'form', dados_fundo: @dados_fundo %>

<%= link_to 'Show', @dados_fundo %> |
<%= link_to 'Back', dados_fundos_path %>

app/views/dados_fundos/index.html.erb
<div class="main">
  <% if(params.has_key?(:cnpj)) %>
  <h3 class="center-align">Rendimentos do ativo <%= params[:cnpj] %></h3>
  <% end %>
  <% if (@ngiri.kind_of?(Array)) %>
  <table id="tabelaRendimentosAtivo" class="centered">
    <tr>
      <th class="center-align">Código</th>
      <th class="center-align">Dia do Pagamento</th>
      <th class="center-align">Rendimento</th>
      <th class="center-align">Data base</th>
    </tr>
    <% @ngiri.each do |item| %>
    <tr class="avisoRendimento dia_<%= item['dataBase'] %>">
      <td class="codigo"><%= item['codigoAtivo'] %></td>
      <td class="diaPagamento"><%= item['diaPagamento'] %></td>
      <td class="rendimento">R$<%= item['rendimento'] %></td>
      <td class="dataBase"><%= item['dataBase'] %></td>
    </tr>
    <% end %>
  </table>
  <% else %>
  <h5><%= @ngiri%></h5>
  <% end %>
</div>

app/views/dados_fundos/new.html.erb
<h1>New Dados Fundo</h1>

<%= render 'form', dados_fundo: @dados_fundo %>

<%= link_to 'Back', dados_fundos_path %>

app/views/dados_fundos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigoativo:</strong>
  <%= @dados_fundo.codigoAtivo %>
</p>

<p>
  <strong>Rendimento:</strong>
  <%= @dados_fundo.rendimento %>
</p>

<p>
  <strong>Data Base:</strong>
  <%= @dados_fundo.dataBase %>
</p>

<p>
  <strong>Dia Pagamento:</strong>
  <%= @dados_fundo.diaPagamento %>
</p>

<p>
  <strong>CNPJ:</strong>
  <%= @dados_fundo.cnpj %>
</p>

<%= link_to 'Edit', edit_dados_fundo_path(@dados_fundo) %> |
<%= link_to 'Back', dados_fundos_path %>