config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :usuarios
  root 'home#index'
  get 'fundos', to: 'fundos#index'
  get 'fundos/:ticker', to: 'fundos#recupera'
  get 'integra/:ticker', to: 'fundos#integra'
  post 'fundos/popula', to: 'fundos#popula'
  resources :dados_fundos
  get 'noticias/fii/:id', to: "noticias#fii"
  get 'noticias/fii/', to: "noticias#fii"

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'sessions#new', as: 'signup'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/views/layouts/_header.html.erb
<div class="navbar-fixed">
	<nav class="light-blue lighten-1" role="navigation">
		<div class="nav-wrapper container"><a id="logo-container" href="/" class="brand-logo flow-text">Poço dos Fundos</a>
			<ul class="right hide-on-med-and-down">
				<li><a href="/">Página Inicial</a></li>
			</ul>
			<ul id="side-fixed" class="sidenav sidenav-fixed">
				<li>
					<div class="user-view">
						<div class="background">
							<%= image_tag('landscape.jpg', :class => "full-image") %>
						</div>
						<% if current_user %>
						<a href="#user">
							<%= link_to root_path do %>
							<%= image_tag('user2.png', :class => "full-image, circle") %>
							<% end %>
							<a href="#name"><span class="white-text name"><%= current_user.nome %></span></a>
							<a href="#email"><span class="white-text email"><%= current_user.email %></span></a>
						</a>
						<% else %>
						<span><h5>Você está deslogado</h5></span>
						<% end %>
					</div>
				</li>

				<% if current_user %>
				<li><a class="subheader"><%= link_to "Log Out", logout_path %></a> </li>
				<% else %>
				<li><%= link_to "Novo Usuário", new_usuario_path %></li>
				<li><%= link_to "Log In", login_path %></li>
				<% end %>
			</ul>
			<a href="#" data-target="side-fixed" class="sidenav-trigger"><i class="material-icons">menu</i></a>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Sin5005</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<%= render "layouts/header" %>
	<%=yield %>
	<%= render "layouts/footer" %>
</body>
</html>